{
  "language": "objective-c",
  "env": {
    "global": [
      "SAUCE_USERNAME=henrikhodne",
      { "secure": "EG4MbxELtWMSfgfbeDVmi88xQESupraH17nqAMkccu86lbPz4NbR/W2I/Hsw6hunEDjTFzgPTUQVJK3ty+HF/w6a4wXgZ3t0d8qRHydG0LJ4PySQZcJaiZwL5lVuUjSgdvSAJB+CSpWwL5AOuPpAkBBx01dAXgaAf+B4tsTPky0=" }
    ]
  },
  "install": [
    "gem install selenium-webdriver",
    "gem install rspec",
    "gem install rest-client"
  ],
  "before_script": [
    "xcodebuild -sdk iphonesimulator6.1 TARGETED_DEVICE_FAMILY=1",
    "zip -r Greeter.app.zip build/Release-iphonesimulator/Greeter.app/",
  "curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY -X POST \"http://saucelabs.com/rest/v1/storage/$SAUCE_USERNAME/Greeter.app.zip?overwrite=true\" -H \"Content-Type: application/octet-stream\" --data-binary @Greeter.app.zip"
  ],
  "script": [
    "rspec AppiumTests/Greeter.rb"
  ]
}
